from __future__ import annotations

"""Validate the synthetic demonstration data generated by app.py.

This test verifies that the in-memory demonstration download contains:

- 16 Bruker-like ``fid`` files;
- 16 matching ``acqus`` files;
- 16 unique FID byte hashes;
- clinical ``study_id`` values matching the NMR sample-folder names exactly.

Run from the repository root with:

    python tests/test_demo_data.py
"""

from hashlib import sha256
from io import BytesIO
from pathlib import Path
import sys
import zipfile

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import _build_demo_clinical_csv, _build_demo_nmr_zip  # noqa: E402


EXPECTED_SAMPLE_COUNT = 16


def _sample_ids_from_archive(names: list[str], filename: str) -> set[str]:
    """Return sample-folder names for archive members ending in ``filename``."""
    suffix = f"/1/{filename}"
    return {
        name[: -len(suffix)]
        for name in names
        if name.endswith(suffix)
    }


def test_demo_archive_and_clinical_ids() -> None:
    """Validate file counts, FID uniqueness, and clinical/NMR ID matching."""
    archive_bytes = _build_demo_nmr_zip()
    clinical_bytes = _build_demo_clinical_csv()

    with zipfile.ZipFile(BytesIO(archive_bytes), "r") as archive:
        names = archive.namelist()

        fid_names = sorted(name for name in names if name.endswith("/1/fid"))
        acqus_names = sorted(name for name in names if name.endswith("/1/acqus"))

        assert len(fid_names) == EXPECTED_SAMPLE_COUNT, (
            f"Expected {EXPECTED_SAMPLE_COUNT} fid files, found {len(fid_names)}."
        )
        assert len(acqus_names) == EXPECTED_SAMPLE_COUNT, (
            f"Expected {EXPECTED_SAMPLE_COUNT} acqus files, found {len(acqus_names)}."
        )

        fid_hashes = {
            sha256(archive.read(name)).hexdigest()
            for name in fid_names
        }
        assert len(fid_hashes) == EXPECTED_SAMPLE_COUNT, (
            "Synthetic FIDs are not all unique: "
            f"found {len(fid_hashes)} unique hashes for "
            f"{EXPECTED_SAMPLE_COUNT} files."
        )

        fid_sample_ids = _sample_ids_from_archive(names, "fid")
        acqus_sample_ids = _sample_ids_from_archive(names, "acqus")

    assert fid_sample_ids == acqus_sample_ids, (
        "The sample folders containing fid files do not exactly match the "
        "sample folders containing acqus files."
    )

    clinical = pd.read_csv(BytesIO(clinical_bytes))
    assert "study_id" in clinical.columns, (
        "The synthetic clinical table is missing the study_id column."
    )

    clinical_ids = set(clinical["study_id"].astype(str))

    assert len(clinical) == EXPECTED_SAMPLE_COUNT, (
        f"Expected {EXPECTED_SAMPLE_COUNT} clinical rows, found {len(clinical)}."
    )
    assert clinical["study_id"].is_unique, (
        "The synthetic clinical table contains duplicate study_id values."
    )
    assert clinical_ids == fid_sample_ids, (
        "Clinical study_id values do not exactly match the NMR sample-folder "
        "names.\n"
        f"Missing from clinical data: {sorted(fid_sample_ids - clinical_ids)}\n"
        f"Missing from NMR archive: {sorted(clinical_ids - fid_sample_ids)}"
    )


def main() -> None:
    test_demo_archive_and_clinical_ids()
    print(
        "Synthetic demo-data test passed: "
        "16 fid files, 16 acqus files, 16 unique FID hashes, "
        "and matching clinical study_id values."
    )


if __name__ == "__main__":
    main()
