from __future__ import annotations

"""Validate the disease-neutral synthetic demonstration data generated by app.py."""

from hashlib import sha256
from io import BytesIO
from pathlib import Path
import sys
import zipfile

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import _build_demo_clinical_csv, _build_demo_nmr_zip  # noqa: E402

EXPECTED_SAMPLE_COUNT = 16
EXPECTED_CLASSES = {"Class_A": 8, "Class_B": 8}


def _sample_ids_from_archive(names: list[str], filename: str) -> set[str]:
    suffix = f"/1/{filename}"
    return {name[: -len(suffix)] for name in names if name.endswith(suffix)}


def test_demo_archive_and_clinical_ids() -> None:
    archive_bytes = _build_demo_nmr_zip()
    clinical_bytes = _build_demo_clinical_csv()

    with zipfile.ZipFile(BytesIO(archive_bytes), "r") as archive:
        names = archive.namelist()
        fid_names = sorted(name for name in names if name.endswith("/1/fid"))
        acqus_names = sorted(name for name in names if name.endswith("/1/acqus"))

        assert len(fid_names) == EXPECTED_SAMPLE_COUNT
        assert len(acqus_names) == EXPECTED_SAMPLE_COUNT

        fid_hashes = {sha256(archive.read(name)).hexdigest() for name in fid_names}
        assert len(fid_hashes) == EXPECTED_SAMPLE_COUNT

        fid_sample_ids = _sample_ids_from_archive(names, "fid")
        acqus_sample_ids = _sample_ids_from_archive(names, "acqus")

    assert fid_sample_ids == acqus_sample_ids

    clinical = pd.read_csv(BytesIO(clinical_bytes))
    required = {"study_id", "Class", "biomarker", "clinical_measure"}
    assert required.issubset(clinical.columns)
    assert "psa" not in {str(c).lower() for c in clinical.columns}
    assert len(clinical) == EXPECTED_SAMPLE_COUNT
    assert clinical["study_id"].is_unique
    assert clinical["Class"].value_counts().to_dict() == EXPECTED_CLASSES
    assert set(clinical["study_id"].astype(str)) == fid_sample_ids


def main() -> None:
    test_demo_archive_and_clinical_ids()
    print(
        "Synthetic demo-data test passed: 16 fid files, 16 acqus files, "
        "16 unique FID hashes, generic class labels, and matching study_id values."
    )


if __name__ == "__main__":
    main()
